### ISSUE TITLE
[cygwin][build] Undefined reference to acct

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [davidgiven/ack#111]
Building in Cygwin 64-bit with make produces the following error

```
util/int/warn.c:109:4: note: in expansion of macro ‘LOG’
    LOG(("@w1 warning: %s [%s: %d]", wmsgtxt, F, L));
    ^~~
util/int+int/main
util/int+int
/tmp/ack-build/obj/util/int/int/main/int/main.a(moncalls.o): In function `moncal                                   l':
/home/Brizio/ACK_INSTALL/ack/util/int/moncalls.c:917: undefined reference to `ac                                   ct'
collect2: error: ld returned 1 exit status
make[1]: *** [/tmp/ack-build/build.make:33809: util/int+int-IMPL] Error 1
make[1]: Leaving directory '/home/Brizio/ACK_INSTALL/ack'
make: *** [Makefile:102: build-plus-goals] Error 2
```

**Comment by davidgiven** [comment]
I've fixed this, but unfortunately the ack still doesn't build on Cygwin; see #88. (Cygwin/Windows don't have `brk()` and `sbrk()`, which the ACK uses.)

**Comment by Fabrizio-Caruso** [comment]
Thanks @davidgiven. Will there be a solution or workaround for a Cygwin build in the next months?
I need Cygwin because it makes my life easier for my project: https://github.com/Fabrizio-Caruso/CROSS-CHASE
Is Lubuntu good enough to build ACK?

**Comment by davidgiven** [comment]
I've seen Cross-Chase --- it's very cool! I should try it out on my new ZX81...

Lubuntu will be fine; but if you want Windows, the ACK builds (relatively) happily in bash-on-windows. I've just integrated Windows CI testing, too, so I can prove it:

https://tea-ci.org/davidgiven/ack/17

**Comment by Fabrizio-Caruso** [comment]
Cool! Thanks @davidgiven ! 
If ACK can compile ANSI C with at least ANSI compliant syntax for pointers to functions, then 
I want it absolutely in my universal tool-chain.
I could support more targets!
I hope there will be a Cygwin-compatible version, though.
I could give bash-on-windows a shot and see if my Makefile is happy with it.

P.S.: CROSS CHASE exists in both real-time and turn-based version, which is sort of similar to the Gnome Robots game. The ZX81 is not using any special graphics, though. The Jupiter Ace version has both graphics and sounds.

**Comment by davidgiven** [comment]
The ACK supports the entire C89 standard (as far as I know), and will compile itself. Function pointers are fully and standardly supported.
