### ISSUE TITLE
[dosbox][question][pc86][imgmount] How do you use pc86 .img files?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [davidgiven/ack#116]
I have not been able to understand how pc86.img files can be used.

I tried IMGMOUNT in DOSBOX and it crashed.
Are there any options I need to provide?

Is DOSBOX the right emulator to use such images?

**Comment by davidgiven** [comment]
They're bootable floppy disk images with no filesystem --- DOSBOX is most likely assuming they contain FAT filesystems and trying to mount them. (It shouldn't crash, though.)

Try `qemu-system-i386 -fd pc86.img`.

**Comment by Fabrizio-Caruso** [comment]
Thanks!
Indeed DOSBOX crashes badly...
Is there any doc on how to use such images? Can they be written to real floppies?

**Comment by davidgiven** [comment]
Yep, look at plat/pc86/README. And yes, they do indeed work on real floppies.

**Comment by Fabrizio-Caruso** [comment]
The -fd does not exist...
qemu-system-i386.exe: -fd: invalid option

**Comment by Fabrizio-Caruso** [comment]
It works with -fda! :-)
Great! I will now try to get my game to work on ACK targets!

**Comment by Fabrizio-Caruso** [comment]
@davidgiven In the doc I read that pc86 is an Intel 8088/86 pc and not a 32-bit 386 or above.
Is it really so or the binary contains 32-bit code not compatible with 8088/8086 cpus?

**Comment by davidgiven** [comment]
It really is 8086 code. (Using the i80 code generator; see mach/i80.)

There's documentation at plat/pc86/README.

**Comment by Fabrizio-Caruso** [comment]
Thanks! I asked because you suggested using a 386 emulator. DOSBOX emulates 8086 and would be a better test but it crashes badly with ACK .img files.

**Comment by davidgiven** [comment]
DOSBOX isn't a PC emulator --- it emulates things at the DOS level only, hence the name. You can't boot disks on it. (Also it emulates 386, 486 etc too.) qemu emulates a PC, and the PC standard requires 8086 code compatibility, so the floppy image works there.

If you really want an 8086-only PC emulator, I actually have one at http://pcemu.sourceforge.net/, although it's very old and rather bitrotted.
