### ISSUE TITLE
[C][bug/feature] multi-line macros not recognized, // comments and CR characters

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [davidgiven/ack#118]
It looks like ACK has a problem with multi-line macros ( macros that are in different lines connected by "\")

I get lots of: 
"\ deleted"
messages.

Is there a way to make them work?

If this feature is really missing, could you please add support for them?

My project uses huge macro statements and it would be impossible to squeeze them in one single line.

Less important missing feature are 
- the modern //  one-line comments, which are not part for modern C and are supported (as an extra) even by many C89-compliant compilers.
- tolerance for CR characters (sometimes coming from Windows editors)

**Comment by davidgiven** [comment]
I don't know what you mean by multiline macros --- do you have an example?

**Comment by Fabrizio-Caruso** [comment]
It is just a way to split long lines with \ at the end of the line
```
...
	#elif defined(__CREATIVISION__) || defined(__MSX__) || defined(__SVI__) \
		|| defined(__ZX81__) || defined(__ZX80__) || defined(__LAMBDA__) \
		|| defined(__SPECTRUM__) || defined(__SC3000__) || defined(__MTX__) \
		|| defined(__APPLE2ENH__) || defined(__APPLE2__) \
		|| defined(__Z9001__) || defined(__P2000__) \
		|| (defined(__ATARI__) || defined(__ATARIXL__)) \
		|| defined(__ATARI5200__) \
		|| defined(__ACE__) \
		|| defined(__CPM_80X24__) \
		|| defined(__EINSTEIN__) \
		|| defined(__OSIC1P__) \
		|| defined(__MC1000__) \
		|| defined(__M5__) \
		|| defined(__AQUARIUS__) \
		|| defined(__COLECO__) \
		|| defined(__PV2000__) \
		|| defined(__PV1000__) \
		|| (defined(__EG2K__) && !defined(UDG_GRAPHICS))  \
		|| (defined(__EG2K__) && defined(UDG_GRAPHICS)) \
|| defined(__ALPHATRO__) || defined(__ABC80__)
...
```

**Comment by Fabrizio-Caruso** [comment]
It seems that little simple things are preventing the integration of ACK into my project.
I could still rewrite all comments, all multi-line macros and remove all CR and see if it works...

Nevertheless it would be good to make ack CR-tollerant and have it support both  // and multiline macros. These are common features. 

P.S: By the way, my project can be complied with GCC with pedantic options with no warnings.

**Comment by Fabrizio-Caruso** [comment]
@davidgiven 
A better example from my code that shows why multi-line macros are necessary:
```
#if !defined(NO_COLOR)
	#define _DRAW(x,y,image) \
	do \
	{ \
		gotoxy((x),(y)); \
		SET_TEXT_COLOR(image->_color); \
		cputc(image->_imageData); \
	} \
	while(0)		
#else
	#define _DRAW(x,y,image) \
	do \
	{ \
		gotoxy((x),(y)); \
		cputc(image->_imageData); \
	} \
	while(0)
#endif
```

**Comment by davidgiven** [comment]
Line continuations and CRLF should be fixed now. I'll have a look at // --- that's a reasonable request (although bear in mind that gcc's `--pedantic` doesn't compile in C89 mode --- try `--std=c89` instead; it'll reject the comments).

**Comment by davidgiven** [comment]
Well, that might work.

The bad news is that the preprocessor is ancient and extremely crufty, and there are lots of special cases which need the single-line comment logic. So it's entirely possible I've missed some. This needs cleaning up. Please try it out and report back if anything doesn't work.

**Comment by Fabrizio-Caruso** [comment]
Thanks a lot! 
I am aware that // comments officially came with C99 but it is an extra feature of most other C89-compliant compilers (e.g., the 8-bit compilers: CC65, Z88DK, CMOC, etc.).
// comments are convinient.

I am going to try again to compile my game and see how far we go this time!

**Comment by Fabrizio-Caruso** [comment]
Everything seems OK! I can (sort of) build my universal game!
The game lacks display routines... I need to figure this out.
