### ISSUE TITLE
After new build: "ack: Cannot find description for fe"

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [davidgiven/ack#121]
I have made
git pull
make clean
make -r -j8 PREFIX=/opt/ack
sudo make PREFIX=/opt/ack/ install

and now the compiler no longer finds the front-ends.
brizio@DESKTOP-I20P8HM:/mnt/c/Retro/CROSS-CHASE/src$ ack -mlinux386 -O ../../ACK/ack/examples/paranoia.c
ack: Cannot find description for fe

By the way the previous build was still in the wrong /tmp directory..., which I deleted it. Maybe it is still installing in the wrong place.

I am going to try to re-compile and see...

**Comment by davidgiven** [comment]
You probably did a built without setting PREFIX correctly --- this is why the instructions say to edit the makefile rather than setting it on the command line; it's very easy to forget and then you end up with a poisoned build tree and you have to clean and rebuild.

**Comment by Fabrizio-Caruso** [comment]
The problem is that ack is always placed in the wrong place:
/tmp/ack-build.

Now I get: 
brizio@DESKTOP-I20P8HM:/mnt/c/Retro/ACK/ack$ sudo ack -lpc86 -O examples/paranoia.c
led: can't read /tmp/ack-build/staging/share/ack/pc86/libpc86 (fatal)

Do 
make
make install
place ack in a tmp directory?

**Comment by Fabrizio-Caruso** [comment]
Ideally
make
make install
should, by default, do something that works.

**Comment by Fabrizio-Caruso** [comment]
I am going to try to build without any PREFIX option.
PREFIX is set to /usr/local in the Makefile.
It suits me fine.

**Comment by davidgiven** [comment]
Please edit the Makefile and set PREFIX there --- it'll avoid these issues.

**Comment by drawkula** [comment]
Building and installing with `make PREFIX=...` does work here. The resulting `ack` finds its friends:
```
(yeti@kumari:15)/home/wrk/runcpm/run/H/1$ /opt/ack/bin/ack -v -v -mcpm -fp -O6 mb.c -o mb.com
/opt/ack/lib/ack/cpp.ansi -D__unix -D__i80 -D__cpm -D__ACK -I/opt/ack/share/ack/cpm/include -I/opt/ack/share/ack/include/ansi -Di80 -DEM_WSIZE=2 -DEM_PSIZE=2 -DEM_SSIZE=2 -DEM_LSIZE=4 -DEM_FSIZE=4 -DEM_DSIZE=8 -D_EM_WSIZE=2 -D_EM_PSIZE=2 -D_EM_SSIZE=2 -D_EM_LSIZE=4 -D_EM_FSIZE=4 -D_EM_DSIZE=8 mb.c
/opt/ack/lib/ack/em_cemcom.ansi -Vw2.1i2.1p2.1f4.1s2.1l4.1d8.1x8.1 -L /tmp/Ack_5c19a.i /tmp/Ack_5c19b.k
/opt/ack/lib/ack/em_opt -m8 /tmp/Ack_5c19b.k
/opt/ack/lib/ack/em_ego -O6 -P /opt/ack/lib/ack/ego /tmp/Ack_5c19c.m
/opt/ack/lib/ack/em_opt2 -m8 /tmp/Ack_5c19d.gk
/opt/ack/lib/ack/cpm/ncg /tmp/Ack_5c19e.g
/opt/ack/lib/ack/cpm/top
/opt/ack/lib/ack/cpm/as - -o mb.o /tmp/Ack_5c19g.so
/opt/ack/lib/ack/em_led -a0:1 -a1:1 -a2:1 -a3:1 -b0:0x0100 /opt/ack/share/ack/cpm/boot.o /opt/ack/share/ack/cpm/c-ansi.o -o /tmp/Ack_5c19h.out mb.o /opt/ack/share/ack/cpm/libc.a /opt/ack/share/ack/cpm/libfp.a /opt/ack/share/ack/cpm/libem.a /opt/ack/share/ack/cpm/libsys.a /opt/ack/share/ack/cpm/libend.a
/opt/ack/bin/aslod /tmp/Ack_5c19h.out mb.com
```
<strike>Maybe</strike>Probably it screws up if you mix building with differend target locations without a `make clean` between the builds.

**Comment by Fabrizio-Caruso** [comment]
Index PREFIX= was the problem for me... somehow...
It has now built correctly with default PREFIX.
