### ISSUE TITLE
[ncurses/conio][feature/question] ncurses/conio lib support?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [davidgiven/ack#122]
I know ACK's goal is not to provide APIs but something semi-standard as a minimal implementation of ncurses and/or conio would provide some tools to do simple console input and graphics.

Does any of the targets supported by ACK have either conio or ncurses libs?

By minimal ncurses and conio I just mean 
- DISPLAY: the ncurses command "move(y,x); refresh();" or the conio-equivalent "gotoxy(x,y)" to move the cursor at position x,y. 
- INPUT: getch/cgetc to read the current status of the keyboard (no cursor and no wait for input)
All the rest can be implemented with stdlib except maybe colors.

Obviously conio can can be implemented by ncurses and ncurses can be (partially) implemented by conio.

**Comment by davidgiven** [comment]
Sorry, that's way out of scope for the ACK to provide itself --- it's not intended to provide a complete SDK for each of its platforms, but instead just the basic compiler, libc and a syscall library. Functionality like conio really belong in a separate project.

**Comment by Fabrizio-Caruso** [comment]
Sure, no worries. Some systems have native control codes to move the cursor. So this can be implemented by simple conio-like macros. Keyboard input (with no wait) would require some extra work, though.
