### ISSUE TITLE
[ansi terminal][dos][question] Escape/control codes 

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [davidgiven/ack#123]
I have managed to build my universal library + game by skipping output routines.

I am now trying to do simple console graphics in dos (pc86) with control codes but no control codes are recognized. I have tried ADM3A, VT52, ANSI/VT100.

Is there an option or some config to get them working? 

I simply want to move the text cursor at a given position.

**Comment by Fabrizio-Caruso** [comment]
I guess this comes from the fact that the pc86 target produces a "barebone" floppy image with no dos-dependencies. 
It would be cool, to have at least some way to move the text cursor through either escape codes or some apis.

**Comment by davidgiven** [comment]
Yeah, the pc86 target simply calls int 0x10 ah=0x0e to draw text --- see https://github.com/davidgiven/ack/blob/default/plat/pc86/libsys/_sys_rawwrite.s. Unfortunately the BIOS doesn't support any useful control codes. (See http://www.ctyme.com/intr/rb-0106.htm.)

Implementing a terminal emulator is out of scope for the pc86 plat; however, you can achieve what you want by manually calling http://www.ctyme.com/intr/rb-0087.htm, http://www.ctyme.com/intr/rb-0099.htm etc.

**Comment by Fabrizio-Caruso** [comment]
THANKS a lot! That is very useful!
