### ISSUE TITLE
[question][tests][binaries] How can I test the binaries (easily)?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [davidgiven/ack#124]
I will be integrating ACK into my tool-chain and abstraction layer.
The goal is to be able to code on all the current targets I support and add all the targets currently supported by ACK. My tool-chain is not just a game. It is a hardware abstraction layer for any sofware.

I will run many tests and report issues. I hope this is OK for you.
It will be beneficial for ACK.

Is there a simple way for me to test the 3 Linux binaries? Can I run them straight from qemu?
Do I need to store them inside a cdrom (image)?
How can I test the pdp11 binary?

**Comment by davidgiven** [comment]
Testing's great --- the ACK's very old, and there are plenty of rough edges which need fixing. Please file as many bugs as you like. (I've just spotted that linux386 binaries seem to seg fault on exit. Need to look into that...)

To run the binaries, you'll probably want an emulator. qemu-user is good at that; it'll let you run alien Linux binaries directly, so you don't need to set up a VM:

    $ qemu-m68k linux68k.exe

The ACK also has built-in emulators used for running the compiler tests for some platforms --- look in, plat/{linux68k,linuxppc,pc86}/emu. They're very very lightweight, supporting very basic I/O only, and also quite slow, but they're built and run automatically so if your tests are simple enough you may be able to use those instead. Look in /tmp/ack-built/obj/plat/linux68k/emu/... for the binary. But they're only suitable for non-interactive tests (programs which run unattended and print some output).

(I'm looking for more emulators, but it's hard to find simple and small enough emulation libraries with the right license; if you find a PDP11 or 386 emulation core, let me know...)

**Comment by Fabrizio-Caruso** [comment]
Thanks!
PDP11 may be emulated by MAME. I wonder how I can run the binary inside of MAME.

**Comment by Fabrizio-Caruso** [comment]
@davidgiven  SUCCESS REPORT!
Thanks to David's fixes (LFCR-issue, multiline and //) I can now build a playable version of my game.
I have made a turn-based pure ANSI stdlib-only version for this purpose.
I will also try to make a real-time pc86-specific version.

I will also try to test the other targets.

David, please keep improving and maintaining ACK!
