### ISSUE TITLE
[m68k][bug] Core-dump when running binary (paranoia example)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [davidgiven/ack#125]
There seems to be a problem with the linux68k target.

I have compiled the text game paranoia from the examples.
It works fine on other targets.

But on the linux86 I get an immediate coredump:

qemu-m68k ./linux68k.exe
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
Illegal instruction (core dumped)

**Comment by davidgiven** [comment]
It works all right for me with qemu 2.12.0; however, I know that older versions of qemu-m68k didn't support the full 68k instruction set, which the ACK uses. Which version of qemu do you have?

**Comment by Fabrizio-Caruso** [comment]
I am using the latest versions in Ubuntu for Windows 10:

qemu-m68k version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.4)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers

**Comment by davidgiven** [comment]
Please zip up and attach your linux68k.exe binary?

**Comment by Fabrizio-Caruso** [comment]
[linux68k.zip](https://github.com/davidgiven/ack/files/2343693/linux68k.zip)

**Comment by davidgiven** [comment]
That runs fine for me, so I'm afraid it must be due to the difference between qemu 2.11.1 and qemu 2.12.

It looks like Ubuntu cosmic, due out in October, will have qemu 2.12, so you may be able to manually install the package from the cosmic development branch.
