### ISSUE TITLE
[linux][qemu] Coredumps with signal 11 on linux 386 & ppc; with signal 4 on linux 68k

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [davidgiven/ack#126]
Maybe qemu is totally broken on all its cores. Is it possible?

I can compile my game on pc86, which works fine and the 3 linux targets but all executables produce cores on qemu (recent version) under Ubuntu on Windows.

brizio@DESKTOP-I20P8HM:/mnt/c/Retro/CROSS-CHASE$ qemu-i386 build/FULL_linux386.exe
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault (core dumped)

brizio@DESKTOP-I20P8HM:/mnt/c/Retro/CROSS-CHASE$ qemu-ppc build/FULL_linuxppc.exe
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault (core dumped)
 
brizio@DESKTOP-I20P8HM:/mnt/c/Retro/CROSS-CHASE$ qemu-m68k build/FULL_linux68k.exe
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
Illegal instruction (core dumped)

**Comment by Fabrizio-Caruso** [comment]
@davidgiven could you please tell me if you can run the builds in the zip file?
[linux_builds.zip](https://github.com/davidgiven/ack/files/2349447/linux_builds.zip)

**Comment by davidgiven** [comment]
They all work absolutely fine for me.

You use bash-for-Windows Linux emulation, don't you? I don't have any actual evidence, but my suspicion is that some of qemu's tricks for jitting the alien machine code isn't working in that environment. You might want to try running them in an ordinary VM and seeing whether that gives you more luck.

**Comment by Fabrizio-Caruso** [comment]
@davidgiven you are both right: bash-for-Windows is the cause but nested virtualization is not supported by qemu.
I may give Virtualbox a shot anyway but I fear it won't help.

So I probably need to run them inside virtualized images... and find a simple way to do this in an automatic way.

**Comment by Fabrizio-Caruso** [comment]
By the way, did the game work?

**Comment by davidgiven** [comment]
Yes; turn based, and I had to hit return before the first screen displayed, so I thought it had hung at first.

**Comment by davidgiven** [comment]
(BTW, the ACK built-in emulators support 68k and PowerPC --- no 386 yet, unfortunately. You could probably easily extend them to to support the extra system calls used by Cross Chase. You probably only need `read()`.)
