### ISSUE TITLE
[cpm][bug?] CPM target may be broken

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [davidgiven/ack#128]
I am compiling the same code (https://github.com/Fabrizio-Caruso/CROSS-CHASE) with Z88DK (which produces Z80) code and ACK (which produces 8080).

I am using Kaypro 2x (which has a Z80 cpu, which should be able to run 8080 code):
mame64.exe kaypro2x -flop1 .\disk\kaypro\k10hald1.td0 -window -uimodekey DEL

In order to load the .COM I use the "quickload" option that is present in recent Mame/Mess versions (you need to wait for the CP/M to complete loading).

I can "quickload" the .com binary created by Z88DK and I get a working game.

If "quickload" the .com binary created by ACK I get a "BAD sector lockout program" error :

![cpm80_error](https://user-images.githubusercontent.com/29057615/45257637-de95bc00-b3a9-11e8-85d7-2db858005524.jpg)

**Comment by davidgiven** [comment]
The screenshot looks unrelated? It looks like you're trying to run the PUTOVL and FINDBAD programs.

Could you attach your compiled binaries from both z88dk and ACK, please?

**Comment by Fabrizio-Caruso** [comment]
It could be a "quickload"-related issue because quickload has been implemented in Mame by one of Z88DK's authors and maybe quickload is making some wrong assumptions...

How can I easily test the cpm 8080 binaries produced by ACK?

ACK: FULL_cpm8080_turn_based.com
Z88DK: FULL_CPM_BUFFERED.COM

[CPM.zip](https://github.com/davidgiven/ack/files/2363718/CPM.zip)

**Comment by davidgiven** [comment]
Another of my compiler projects has a simple CP/M emulator --- you'll need to build it yourself, though. https://github.com/davidgiven/cowgol/tree/master/emu/cpm.

That runs both binaries fine (although the z88dk one needs me to press the RETURN key five times before the first screen appears).

Alternatively, use cpmtools (it's in Ubuntu) to push the .com files into MAME's emulated disk image. It's possible that MAME's quickload can't handle a binary that big --- 48kB is a lot for CP/M; trying to load via the emulated disk will find this out.

**Comment by davidgiven** [comment]
(PS. If you're not already doing so, compiling with the -O6 option should produce smaller binaries.)

**Comment by drawkula** [comment]
> How can I easily test the cpm 8080 binaries produced by ACK?

I like RunCPM because the CP/M filesystem is mapped to a directory structure instead of having image files per CP/M drive. This comes at the cost of a very custom BIOS and boot method but so far it is extremely handy.

—▷ https://github.com/MockbaTheBorg/RunCPM

...and MIT licensed is a big plus too... :-)

When in doubt that RunCPM might be picky with some binaries, I test them on AltairZ80. It uses image files for the drives but the transfer to and from them is easy using some CP/M utilities which can pass the files to the host's filesystem so external cpmtools aren't needed to do this.

—▷ https://schorn.ch/altair.html

**Comment by Fabrizio-Caruso** [comment]
Thanks guys!

@davidgiven 
Even though the Z80 instruction set may make the binaries more compact,
it seems ACK is producing huge binaries compared to Z88DK.

ACK -O6 -> 48505
Z88DK -> 17000-18000 depending on optimizations

**Comment by Fabrizio-Caruso** [comment]
@drawkula 
RunCPM does not build...
"
...
lua.c:80:10: fatal error: readline/readline.h: No such file or directory
 #include <readline/readline.h>
"

**Comment by drawkula** [comment]
Try:
```
$ sudo apt-get install libreadline-dev libncurses-dev
```

**Comment by Fabrizio-Caruso** [comment]
@drawkula, I had libncurses-dev, which is the only mentioned dependency in the Readme.
 but not libreadline. 
Now it fails because of missing Lua dependencies...
I need to figure out which packages I need...
Why lua package should I get?

**Comment by Fabrizio-Caruso** [comment]
@drawkula I have installed lua5.3 but I get:
...
lua.o: In function `docall':
lua.c:(.text+0x74): undefined reference to `lua_gettop'
lua.c:(.text+0x8a): undefined reference to `lua_pushcclosure'
lua.c:(.text+0x99): undefined reference to `lua_rotate'
lua.c:(.text+0xc7): undefined reference to `lua_pcallk'
lua.c:(.text+0xe5): undefined reference to `lua_rotate'
lua.c:(.text+0xf2): undefined reference to `lua_settop'
lua.o: In function `lstop':
lua.c:(.text+0x14b): undefined reference to `lua_sethook'
lua.o: In function `msghandler':
lua.c:(.text+0x17c): undefined reference to `lua_tolstring'
lua.c:(.text+0x194): undefined reference to `luaL_traceback'
lua.c:(.text+0x1b0): undefined reference to `luaL_callmeta'
lua.c:(.text+0x1c1): undefined reference to `lua_type'
lua.c:(.text+0x1d3): undefined reference to `lua_type'
lua.c:(.text+0x1dd): undefined reference to `lua_typename'
lua.c:(.text+0x1f1): undefined reference to `lua_pushfstring'
...

**Comment by drawkula** [comment]
These versions are installed here:
```
$ ls -l /var/lib/dpkg/info/liblua5.*.list
-rw-r--r-- 1 root root 413 Aug 29 12:09 /var/lib/dpkg/info/liblua5.2-0:amd64.list
-rw-r--r-- 1 root root 360 Aug 29 12:14 /var/lib/dpkg/info/liblua5.3-0:amd64.list
```
And I think RunCPM uses the 5.2 version.

**Comment by Fabrizio-Caruso** [comment]
I also see liblua but only 5.2 despite the fact that I installed 5.3 and that is what apt-get install reports as present.
This is a painful installation process.
This https://github.com/jhallen/cpm
works straightaway.
Just "make" and it builds.
Need to figure out how to use it, though.

**Comment by drawkula** [comment]
I don't have problems on Debian with RunCPM.

https://github.com/jhallen/cpm hooks into the output and translates ADM-3A terminal commands to the ones Linux expects:

> This is a modified version of Parag Patel's CP/M emulator. This version includes a filter/emulator for an ADM-3A terminal as emulated by a Kaypro 2x. Basically it converts ADM-3A codes into ANSI codes on output and converts arrow keys and PgUp / PgDn into WordStar motion keys on input.

AltairZ80 and RunCPM just pass through what CP/M sends. That is what I prefer. That does not tranlate the modern special keys and you mainly need to stick to the well known control command keys to get along with full screen CP/M programs.

If you want a longer journey, https://www.autometer.de/unix4fun/z80pack/index.html and http://www.mathematik.uni-ulm.de/users/ag/yaze-ag deserve a visit too.

**Comment by Fabrizio-Caruso** [comment]
@drawkula I want what you propose but it does not build...
I am stuck at the lua issues. There is another guy who has opened a similar issue.
Maybe the author can clean this up.

**Comment by Fabrizio-Caruso** [comment]
@drawkula Anyway https://github.com/jhallen/cpm is better than nothing for simple testing.
Input is not ok. There is a PR that improves on that.

**Comment by Fabrizio-Caruso** [comment]
@drawkula  This is now a bit off-topic. Is there a decent emulator for the Kaypro? Mame has many bugs and the screen emulation is broken. Any other option?

**Comment by drawkula** [comment]
I don't know a special Kaypro emulator.

**Comment by davidgiven** [comment]
Re code size: remember that the ACK produces 8080 code, which is less dense that Z88DK's Z80 code. But that shouldn't account for all the size difference; looking at the disassembly, z88dk doesn't use ix and iy much. I bet what's happening is that something is pulling in `printf`, which will in turn pull in the floating point library. (Compiling examples/hilo.c produces a 33kB binary.)

Could you compile your program with `-v -t` --- which will preserve intermediate files --- and then send me the `.out` file, please? This will contain symbol information so I can see what's there.

Regarding CP/M emulation: remember that just about _all_ the old Z80-based machines ran CP/M, so you don't need a specific emulator. You could, for example, use an off-the-shelf TRS-80 emulator and then install CP/M on it (http://www.manmrk.net/tutorials/TRS80/Software/cpm/index.htm). If you already have an emulator set up in your test environment that may be a good candidate.The Amstrad CPC, too.

**Comment by Fabrizio-Caruso** [comment]
I will do the tests you suggest as soon as I can.

The huge binary size difference is not explained by the density as I also mentioned. I get a 12k binary if I compile for the 6502 with CC65.

Indeed it looks like there is some huge overhead that does not depend much on the size of my source code: if I compile the tiny version of my game with CC65 I get a 3k binary vs 37k binary with ack.

  Fabrizio


--
Inviato da myMail per Android

domenica, 09 settembre 2018, 00:06PM +02:00 da David Given notifications@github.com<mailto:notifications@github.com>:


Re code size: remember that the ACK produces 8080 code, which is less dense that Z88DK's Z80 code. But that shouldn't account for all the size difference; looking at the disassembly, z88dk doesn't use ix and iy much. I bet what's happening is that something is pulling in printf, which will in turn pull in the floating point library. (Compiling examples/hilo.c produces a 33kB binary.)

Could you compile your program with -v -t --- which will preserve intermediate files --- and then send me the .out file, please? This will contain symbol information so I can see what's there.

Regarding CP/M emulation: remember that just about all the old Z80-based machines ran CP/M, so you don't need a specific emulator. You could, for example, use an off-the-shelf TRS-80 emulator and then install CP/M on it (http://www.manmrk.net/tutorials/TRS80/Software/cpm/index.htm). If you already have an emulator set up in your test environment that may be a good candidate.The Amstrad CPC, too.

**Comment by Fabrizio-Caruso** [comment]
@davidgiven The compilation produced only one .out file with the name of just one of the source files.
 
I have included all the files in the attached .zip file.

[compilation.zip](https://github.com/davidgiven/ack/files/2364477/compilation.zip)

**Comment by davidgiven** [comment]
Yup, that's normal. The `.out` file is an ACK binary which is then converted to a CP/M executable.

It looks like your program stops at about 0x5000, and everything from there up to 0xc000 is the standard library. Your program appears to refer to printf which is causing stdio, all the integer/floating point conversion routines, malloc/free etc to be pulled in. If you can avoid calling printf the binary should get much smaller. (Call `write()` on fd 1 to efficiently send text to the screen.)

**Comment by Fabrizio-Caruso** [comment]
@davidgiven  Thanks a lot!

Replacing an innocent-looking printf("\n") with putchar('\n') produces a much smaller binary:
printf("\n") -> 48K
putchar('\n') -> 25k

This is still about 50% bigger than what CC65 (6502) or Z88DK (Z80) produce, but it is very reasonable. :-)

Ideally it would be good to have stdio at a reasonable cost when one few of its functions/features are used. In my case I had a single printf("\n"), which was costing 23k.

Is ACK using operating system routines (if they exist) to reduce the size of the binary? 

Other 8-bit compilers have options to selectively disable some stdio functions in order to reduce the binary size.
Could something similar be possible with ACK?

**Comment by davidgiven** [comment]
Yeah, having a restricted stdio does make sense on platforms like CP/M. The trouble is, it's hard to know what to restrict... printf() is fundamentally an interpreter so there's no way the linker can know that you don't actually want, e.g., the ability to print floating point numbers. And it's intrinsically tied to stdio, which requires dynamically allocated buffers etc.

The only sensible way to do this is to build multiple libcs with various features and then have the user select one at link time. It wouldn't be hard to do --- I've filed #129.

**Comment by Fabrizio-Caruso** [comment]
@davidgiven Thanks a lot!
Z88DK can selectively disable unused formatters through manual settings with pragmas and/or compilation options.
CC65 does something similar but has no float support, which alone, saves a lot of memory.

**Comment by Fabrizio-Caruso** [comment]
@davidgiven what I suggest is to remove unused portions of the lib after compilation when the user decides so with some pragmas or compilation options. The user/coder knows that printf/scanf won't receive any %d or any %s and can tell the linker to avoid those.

**Comment by Fabrizio-Caruso** [comment]
@davidgiven I am closing this issue because the CP/M target is not broken. It is just using emiting an unnecessarily large binary that makes it less usable due to the memory constraints of the target. This issue is tracked by #129.
