### ISSUE TITLE
sbrk issues: sbrk(int) vs sbrk(intptr_t)

### ISSUE THREAD

**Issue by kernigh** [davidgiven/ack#13]
Is it sbrk(int) or sbrk(intptr_t)? Our libsys and libcc.ansi use intptr_t, but our libpc and libm2 use int. This will become a problem if we add a platform where int and intptr_t have different sizes.

I have been using OpenBSD's manual pages as a reference. OpenBSD says sbrk(2) takes an int and sets errno = ENOMEM on failure. Some of our libsys implementations don't set errno.

Our ncg tables have broken rules for lor 2, str 2 to load/store the EM heap pointer. These are broken because they don't use sbrk. We only use lor 2, str 2 in the Pascal library, and only for the mark, release keywords. Seems that new, dis got fixed to use sbrk; but mark, release never got fixed.

Our brk() for Linux fails to update the value of sbrk(0).

It seems that calloc() went missing from libcc.ansi after the memory allocator got replaced.

**Comment by davidgiven** [comment]
Re sbrk(): it should do whatever the standard says it does. The Posix standard removed sbrk in 2001. So, um.

I used the Linux man pages as a reference here, which use intptr_t. I think that going with OpenBSD and using int is simpler.

Re errno and sbrk(0): yeah, not surprised. Thanks; will fix.

ncg tables: I suppose the cleanest thing to do is to update the code generator to produce calls to brk() or sbrk() when reading or writing it, but I suspect the easiest thing to do is to update the mark and release keywords in the Pascal library and then just call the heap pointer obsolete.

Ideally I'd like to get rid of brk() and sbrk() completely, in favour of a something which can request non-contiguous memory blocks from the operating system, but I know that's unlikely to happen anytime soon.

Re calloc(): oops. Sorry.

**Comment by davidgiven** [comment]
The brk(), sbrk() and calloc() issues should (I hope) be solved now --- I even wrote some tests. I'll think about Pascal.

**Comment by davidgiven** [comment]
So what I've done is lose Mark() and Release() completely. They never worked, and New() and Dispose() are supported anyway.

And there's a test!
