### ISSUE TITLE
Object format of PC86

### ISSUE THREAD

**Issue by YuHuangjie** [davidgiven/ack#134]
Hi,

Are there any descriptions of object file formats? Suppose I have generated an object file _boot.o_ with

`ack -mpc86 -c boot.c -o boot.o`

What's the format of boot.o? Is it ELF or a.out? 

Thanks

**Comment by davidgiven** [comment]
Neither! It's ack.out, the ACK's own object file format. It's described it
util/led/ack.out.5, so do:

man -l util/led/ack.out.5

...to read it. See also modules/src/object/object.3 for the helper library
for manipulating ack.out files.
