### ISSUE TITLE
Build fails: no rule to make util/ego/share/aux.c

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [davidgiven/ack#138]
I can no longer builc ack under Lubuntu

It fails with errors:
No rule to make target util/ego/share/aux.c
...
Recipe for target build-plus-goals failed
Error 2

**Comment by davidgiven** [comment]
Are you on Windows, by any chance? aux is a reserved filename word (with some Windows APIs) and can't reliably use it in filenames.

**Comment by Fabrizio-Caruso** [comment]
Under virtualized Lubuntu 64 bit  under Windows 10

**Comment by Fabrizio-Caruso** [comment]
I downloaded the zip and did not perform a clone

**Comment by davidgiven** [comment]
Hmm. Works for me. Did that aux.c file ever touch the WIndows filesystem --- e.g. did you unzip it with Windows? Using a virtualised filesystem hosted on Windows? Download the zipfile from Windows?

We should rename it anyway to prevent future problems, but it'd be good to know exactly what went wrong.

**Comment by Fabrizio-Caruso** [comment]
Yes, it was downloaded from Windows and unzipped in Ubuntu on a shared directory in Windows

**Comment by davidgiven** [comment]
Try it in an Ubuntu native filesystem (/tmp will probably do).

**Comment by Fabrizio-Caruso** [comment]
It works if I unzip in a non-shared folder. This is annoying but not a real bug

**Comment by Fabrizio-Caruso** [comment]
I am closing this but please consider fixing this misbehavior

**Comment by davidgiven** [comment]
Yup, will do. It's really a Windows bug but we don't want to be provoking it.
