### ISSUE TITLE
[bug] ncgg calls n_coerc() procedure with an extra parameter

### ISSUE THREAD

**Issue by ccodere** [davidgiven/ack#188]
While creating to function prototypes for ncgg, it seems that n_coerc in cgg.y line 615 is called with one less parameter. I have no clue what should be the correct value.

**Comment by davidgiven** [comment]
I think it's supposed to be optional (allowed in K&R C). Looking at the code in coerc.c the `in` parameter is only used if `ti` is 0, which matches what the code's doing. I'd just pass in 0 in the case where it's not used.

**Comment by ccodere** [comment]
Sorry, my mistake, the issue is on another line.of cgg.y: n_coerc($3,$5,$6,$7,$8), any advice on this one?
