### ISSUE TITLE
tests/plat/testdriver.sh[48]: timeout: not found

### ISSUE THREAD

**Issue by kernigh** [davidgiven/ack#19]
```
FAILED: /home/kernigh/park/ack-build/obj/plat/qemuppc/tests/from_si_to_d_e/stamp 
tests/plat/testdriver.sh qemu-system-ppc /home/kernigh/park/ack-build/obj/plat/qemuppc/tests/from_si_to_d_e_bin/from_si_to_d_e_bin 5 && touch /home/kernigh/park/ack-build/obj/plat/qemuppc/tests/from_si_to_d_e/stamp 
tests/plat/testdriver.sh[48]: timeout: not found
```

The build fails just because I run OpenBSD and I haven't installed a timeout command. I'm working around this disabling all the tests: I comment out lines in build.lua so vars.plats_with_tests becomes an empty list.

It seems odd to run the tests during a build. What if a test fails but I still want to build ack? I suggest to move the tests from `gmake` to `gmake test`.

**Comment by kernigh** [comment]
The timeout code in `testdriver.sh` is a mess:

```sh
        ( $method -nographic $img 2>&1 & echo $! > $pidfile ) \
            | tee $result \
            | ( timeout $timeout grep -l -q @@FINISHED ; echo ) \
            | ( read dummy && kill $(cat $pidfile) )
```

There's a race between `echo $! > $pidfile` and `kill $(cat $pidfile)`. The system might run cat before echo, so we might read the pidfile before we write it, and kill the wrong process.

There's another race if qemu exits before we kill it. The subshell that forked qemu then writes the pidfile and exits, so qemu becomes an orphaned process. Then the system init collects qemu's exit status and frees its pid. This might happen before we kill the pid in the pidfile. Then the pid might not exist, or might get recycled by a different process, so we might kill the wrong process.

**Comment by davidgiven** [comment]
Yes, it's a mess --- it was intended as a quick hack to prove the concept. I thought I'd managed to iron out most of the race conditions, but obiously not. It's far to easy to forget that `$(...)` executes out of order in a pipeline. This needs to be rewritten in a real language.

I do have an OpenBSD box, and do test builds on that; but I didn't try the case that someone had qemu installed but not timeout (which I thought was Posix).

This branch:

https://github.com/davidgiven/ack/tree/dtrg-tests

...should contain a custom tool that replaces both timeout and the hacky pipeline. It runs on OpenBSD, but I don't have qemu (haven't figured out how to make pkg_add install it on a headless machine yet). PTAL?

**Comment by kernigh** [comment]
If your headless OpenBSD machine is missing the X libraries in /usr/X11R6/lib, then you need to install xbase60.tgz from the base sets. pkg_add doesn't install base sets. [This FAQ entry](http://www.openbsd.org/faq/faq4.html#FilesNeeded) says to install base sets by booting bsd.rd and choosing upgrade.

Trying your branch dtrg-tests. It builds! All the tests passed or got skipped, I guess. I don't see a summary of the test results.

The signal handler in util/build/testdriver.c isn't safe, because it calls exit() after longjmp(), and exit() isn't safe. If I get unlucky, SIGALRM might arrive during `fputs(buffer, stdout)`, leaving stdio in a bad state. Then exit() would try to flush stdout, but that would crash, because the fputs() never returned. But if we remove the longjmp() and use that timed_out variable, then SIGALRM might arrive after the `while (!timed_out)` checks the flag but before fgets() blocks on the pipe, so we would get stuck.

Here's my idea: put a kill() in the signal handler. This kill() closes the pipe, so the fgets() reads end of file.

```diff
diff --git a/util/build/testrunner.c b/util/build/testrunner.c
index 16d526d..709ac64 100644
--- a/util/build/testrunner.c
+++ b/util/build/testrunner.c
@@ -9,10 +9,9 @@
 #include "diagnostics.h"
 
 static bool timed_out = false;
-static bool child_exited = false;
-static char** command = NULL;
+static char* const* command = NULL;
 static int timeout = 0;
-static jmp_buf exit_jmp;
+static pid_t pid;
 
 static void parse_arguments(int argc, char* const argv[])
 {
@@ -44,7 +43,7 @@ static void parse_arguments(int argc, char* const argv[])
 static void sigalrm_cb(int sigraised)
 {
     timed_out = true;
-    longjmp(exit_jmp, 1);
+    kill(pid, SIGKILL);
}
 
 int main(int argc, char* const argv[])
@@ -53,22 +52,21 @@ int main(int argc, char* const argv[])
     const int WRITE = 1;
 
     int fds[2];
-    int pid;
     FILE* childin;
     int wstatus;
     char buffer[4096];
 
     parse_arguments(argc, argv);
 
-    if (setjmp(exit_jmp) == 0)
+    if (true)
     {
         /* First time through. */
 
-        signal(SIGALRM, sigalrm_cb);
-        alarm(timeout);
-
-        pipe(fds);
+        if (pipe(fds) < 0)
+            fatal("can't make pipes");
         pid = fork();
+        if (pid < 0)
+            fatal("can't fork");
         if (pid == 0)
         {
             /* Child */
@@ -80,8 +78,14 @@ int main(int argc, char* const argv[])
             _exit(1);
         }
 
+        close(fds[WRITE]);
+        signal(SIGALRM, sigalrm_cb);
+        alarm(timeout);
+
         childin = fdopen(fds[READ], "r");
-        while (!timed_out)
+        if (!childin)
+            fatal("can't open pipe");
+        while (true)
         {
             if (!fgets(buffer, sizeof(buffer), childin))
                 break;
@@ -96,6 +100,7 @@ int main(int argc, char* const argv[])
 
     /* Reached via longjmp, EOF, or seeing a @@FINISHED. */
 
+    alarm(0);
     kill(pid, SIGKILL);
     waitpid(pid, &wstatus, 0);
     if (timed_out)
```

**Comment by davidgiven** [comment]
Yup, done. (I could have sworn that you could longjmp out of a signal handler to return to normal process state --- not sure where I picked that up from.)

Re running the tests as part of the build: that's what I'm used to in other systems; it guarantees that the tests actually get run. A failing test causes a failing build. The test framework does need a bit of enhancement to include blacklisting tests and running all the tests, producing a summary at the end, but I don't really have any strong opinions here. It'd be trivial to split into two passes. I'll have a look.
