### ISSUE TITLE
Why does this compile?

### ISSUE THREAD

**Issue by drawkula** [davidgiven/ack#205]
```
$ cat bad.b
main() {
  auto i,m,x,y;

  m = 4;
  x = 0;
  y = 0;
  i = 0;
  while( i<m && x+y<=16384 ) {
    printf("%d*n",i);
    i++;
  }
}
$ /opt/ack/bin/ack -mlinux386 bad.b -o bad
$ ./bad 
$ # no output
```
B seems not to have `&&` like C. That's ok. But why does `ack` throw no error here?

I stumbled over this while chiselling [a Mandelbrot set example in B](https://rosettacode.org/wiki/Mandelbrot_set#B) for Rosetta Code.

**Comment by davidgiven** [comment]
Ooh, nice --- been a while since I saw some code quite so misleading... it parses like this:

`while ((I<m) & ((&x+y) <= 16384))`

Sadly I think that's WAI.

**Comment by drawkula** [comment]
Thanks!
