### ISSUE TITLE
hilo.mod broken on powerpc

### ISSUE THREAD

**Issue by kernigh** [davidgiven/ack#22]
hilo.mod doesn't work on powerpc platforms. I remember that it worked in the past.

I built f1c357b from the default branch and copied staging/share/ack/examples/hilo_mod.linuxppc to my PowerPC Linux machine (a qemu-system-ppc running Debian). After I enter my name, the program enters an infinite loop until I hit ^C:

```
kernigh@lip:~$ ./hilo_mod.linuxppc 

Hi there! I'm written in Modula-2. Before we start, what is your name?
> George
...
> 
Try a bit higher.
> 
Try a bit higher.
> 
Try a bit higher.
^CSegmentation fault
```

I built 969e98b from my Mac OS X branch and copied hilo_mod.osxppc to my PowerPC Mac. It has the same problem:

```
Ghostborough:~/mack kernigh$ ./hilo_mod.osxppc 

Hi there! I'm written in Modula-2. Before we start, what is your name?
> George
...
> 
Try a bit higher.
> 
Try a bit higher.
> 
Try a bit higher.
> ^C"lang/m2/libm2/Traps.mod", line 54: got a unix signal
```

I get a message from Traps.mod in Mac OS X but a "Segmentation fault" in Linux. This might be a bug with signal handlers: Linux puts the signal number in register r3 but ACK reads it from 0(r1).

I also tried hilo_mod.osx386 (from my Mac OS X branch) on an Intel Mac. It doesn't have the bug, so I can guess numbers as usual. I also tried hilo_mod.pc86 (from the default branch) in qemu-system-i386. It doesn't have the bug. I only get the bug with PowerPC.

**Comment by kernigh** [comment]
$ git bisect bad
f8fa3ece4241a1892505cd5270bdfadca2a82604 is the first bad commit

**Comment by kernigh** [comment]
InOut can't find the whitespace after my input string. It uses EM instruction `inn 32` to check if a CHAR is in a SET OF CHAR. This doesn't work. Here's a test program.

```mod
MODULE inspace;
FROM InOut IMPORT WriteLn, WriteString;

TYPE charset = SET OF CHAR;

PROCEDURE Space(c: CHAR): BOOLEAN;
BEGIN
  RETURN c IN charset{' ', 11C, 12C, 15C}
END Space;

BEGIN
  IF Space('a') THEN
    WriteString("fail 1");
    WriteLn;
  END;
  IF NOT Space(' ') THEN
    WriteString("fail 2");
    WriteLn;
  END;
  IF NOT Space(12C) THEN
    WriteString("fail 3");
    WriteLn;
  END;
END inspace.
```

In default f1c357b, this prints "fail 2" and "fail 3". In 2d0bc7e (the last commit before f8fa3ec broke hilo.mod), this prints only "fail 2".

**Comment by davidgiven** [comment]
That probably happened when I changed .inn to work with mcg. Which is kind of odd, because I wrote a test for that...

Will investigate; thanks.

**Comment by davidgiven** [comment]
inn handles big-endian platform incorrectly; I was assuming the bitset is an array of bytes, when actually it's an array of quads. This means that on big-endian systems the order of the bytes in each word is inverted.
