### ISSUE TITLE
plats need to depend on the language compilers

### ISSUE THREAD

**Issue by davidgiven** [davidgiven/ack#24]
They already depend on the language _libraries_, but not the compilers, which are built by the top-level build.lua --- so there's a race between what gets built first. We should refactor so that each plat depends on all the tools it needs. This would fix the race, and also allow plats to be built one at a time.

**Comment by kernigh** [comment]
Because of ackfile in plat/build.lua, I believe that the language libraries depend on the compilers for C, Pascal, Modula-2, but not for Basic. The race is to complete the Basic compiler before we compile any Basic file. I suggest to add the Basic compiler to ackfile's deps.

**Comment by davidgiven** [comment]
Fixed as a byproduct of a43258fe9d2668e524f55dd7f0a6b768ce41e005.
