### ISSUE TITLE
qemuppc won't run tests bigger than 4kB

### ISSUE THREAD

**Issue by davidgiven** [davidgiven/ack#26]
It looks like qemu only loads (or at least, maps) the bottom 4kB of the kernel. So far our tests haven't been big enough to hit this limit, but now we have a big one (written in Modula-2) which is about 20kB, and won't run.

I've turned off qemuppc test running for the time being.

**Comment by kernigh** [comment]
There isn't always a 4kB limit. This program is about 40kB, but does run:

```c
#include <unistd.h>

char huge[40000] = { 'Z' };
char c = 'A';
char n = '\n';

int main(void) {
        write(1, &c, 1);
        write(1, &n, 1);
        c = 'B';
        write(1, &c, 1);
        write(1, &n, 1);
        return 0;
}
```

```
$ ack -mqemuppc -o change change.c
$ qemu-system-ppc -kernel change                                               
```

It prints A, newline, B, newline. The program is a raw memory dump, not an ELF file. Inspection with `od -ta change | tail` reveals that the A, newline, are near the end of the file, after the huge array.

**Comment by davidgiven** [comment]
That's weird. The modula-2 test case you gave me crashed on qemuppc; connecting up gdb showed that the first 4kB was mapped, but nothing else was (gdb errored out trying to read that memory).

This works too, and it's a 120kB binary, all code (checking to see whether it's something to do with executable bits):

```
#include <unistd.h>

int counter = 0;

#define TEN(X) X; X; X; X; X; X; X; X; X; X;

int main(void) {
	write(1, "A\n", 2);

	TEN(TEN(TEN(TEN(counter++))))

	write(1, "B\n", 2);
	return 0;
}
```

So I reckon this must be just gdb lying to me, then.

However, the Modula-2 test still doesn't work on qemuppc.

**Comment by kernigh** [comment]
This diff seems to fix the test by removing InOut and calling the C functions fail() and finished(). qemuppc uses mcg. When I last checked, mcg can't do printf("%d\n", 0) in C. I wonder if mcg also can't do InOut in Modula-2?

The counter in the test summary always says "0 failed". To check if bug-22 failed, I needed to dig through the testlog files. The file tests/plat/lib/build.lua seems to go unused, so I edited tests/plat/build.lua instead.

```diff
diff --git a/tests/plat/bugs/bug-22-inn_mod.mod b/tests/plat/bugs/bug-22-inn_mod.mod
index 8f3a2d0..b6adb4a 100644
--- a/tests/plat/bugs/bug-22-inn_mod.mod
+++ b/tests/plat/bugs/bug-22-inn_mod.mod
@@ -1,5 +1,5 @@
 MODULE test;
-FROM InOut IMPORT WriteLn, WriteString;
+FROM Test IMPORT fail, finished;
 
 TYPE charset = SET OF CHAR;
 
@@ -10,17 +10,13 @@ END Space;
 
 BEGIN
   IF Space('a') THEN
-    WriteString("@@FAIL 1");
-    WriteLn;
+    fail(1);
   END;
   IF NOT Space(' ') THEN
-    WriteString("@@FAIL 2");
-    WriteLn;
+    fail(2);
   END;
   IF NOT Space(12C) THEN
-    WriteString("@@FAIL 3");
-    WriteLn;
+    fail(3);
   END;
-  WriteString("@@FINISHED");
-  WriteLn;
-END test.
\ No newline at end of file
+  finished;
+END test.
diff --git a/tests/plat/build.lua b/tests/plat/build.lua
index d8362b3..06612fd 100644
--- a/tests/plat/build.lua
+++ b/tests/plat/build.lua
@@ -18,7 +18,10 @@ definerule("plat_testsuite",
 		acklibrary {
 			name = "lib",
 			srcs = { "tests/plat/lib/test.c" },
-			hdrs = { "tests/plat/lib/test.h" },
+			hdrs = {
+				"tests/plat/lib/test.h",
+				"tests/plat/lib/Test.def",
+			},
 			vars = { plat = e.plat },
 		}
 
diff --git a/tests/plat/lib/Test.def b/tests/plat/lib/Test.def
index e69de29..cab31f2 100644
--- a/tests/plat/lib/Test.def
+++ b/tests/plat/lib/Test.def
@@ -0,0 +1,6 @@
+(*$Foreign*)
+DEFINITION MODULE Test;
+  PROCEDURE finished();
+  PROCEDURE writehex(code: LONGINT);
+  PROCEDURE fail(code: LONGINT);
+END Test.
```

**Comment by davidgiven** [comment]
Yup, works fine --- thanks. I've updated the test and reenabled testing for qemuppc.

It must have been gdb lying to me. I like this kind of bug, as they're really easy to fix...
