### ISSUE TITLE
Recent version fail to compile with a sig 11 on em_m2

### ISSUE THREAD

**Issue by tsupplis** [davidgiven/ack#261]
[4127/10116] ACKDIR=/tmp/ack-build/sta...build/obj/lang/m2/include/headers -O6 
FAILED: /tmp/ack-build/obj/lang/m2/libm2/lib_msdos86/Storage/Storage.o 
ACKDIR=/tmp/ack-build/staging /tmp/ack-build/staging/bin/ack -mmsdos86 -c.o -o /tmp/ack-build/obj/lang/m2/libm2/lib_msdos86/Storage/Storage.o lang/m2/libm2/Storage.mod -I/tmp/ack-build/obj/h/emheaders -I/tmp/ack-build/obj/lang/m2/include/headers -O6 
/tmp/ack-build/staging/bin/ack: /tmp/ack-build/staging/lib/ack/em_m2 died with signal 11
[4136/10116] ACKDIR=/tmp/ack-build/sta...build/obj/lang/m2/include/headers -O6 
ninja: build stopped: subcommand failed.
make: *** [build-plus-goals] Error 1

Build done System OSX 12. This is regression compared to June timeframe

**Comment by davidgiven** [comment]
I've just done a bunch of work to get this running on Windows, so this could be related. However, the CI systems builds on OSX 11, so I know it works there: https://github.com/davidgiven/ack/runs/7419357400?check_suite_focus=true

**Comment by tsupplis** [comment]
ok. I was able to compile. issue is of my own doing using wrong compile.

**Comment by davidgiven** [comment]
Good to know --- thanks for updating!
