### ISSUE TITLE
Fails tests on my ArchLinux

### ISSUE THREAD

**Issue by mxlgv** [davidgiven/ack#273]
I installed all the latest packages. And run make. It gave me:

**** /tmp/ack-build/obj/plat/linuxmips/tests/tests/linuxmips-pascalsets_p-testlog.txt
@@FAIL by testdriver.sh

**** /tmp/ack-build/obj/plat/linuxmips/tests/tests/linuxmips-from_d_to_ui_e-testlog.txt
@@FAIL by testdriver.sh

**** /tmp/ack-build/obj/plat/linuxmips/tests/tests/linuxmips-from_ui_to_d_e-testlog.txt
@@FAIL by testdriver.sh

320 tests passed
3 tests failed to pass
0 were skipped (see build log for details)
0 timed out
3 failed

**Comment by someordinaryidiot** [comment]
I have the same problem.

**Comment by davidgiven** [comment]
That's one of the qemu tests. They're horribly flaky. I think I'm actually going to disable them all, as I don't think they're worth it.
