### ISSUE TITLE
Incorrect error message for invalid function call for Modula-2

### ISSUE THREAD

**Issue by dram** [davidgiven/ack#30]
For following Modula-2 code:

```
MODULE test;

IMPORT Arguments;

VAR
  program: ARRAY [0..1024] OF CHAR;

BEGIN
  Arguments.Argv (0, program);
END test.
```

ACK report following error:

```
"test.mod", line 9: procedure call expected instead of function call
```

Which I think should be "function call expected instead of procedure call", as `Arguments.Argv` has a return value.

BTW, this message was changed to current form by commit 7f9fd96 in 1988.

**Comment by davidgiven** [comment]
I think this is correct --- `Arguments.Argv` has a return value, which makes it a function, which you can't call as a top-level statement without storing its result somewhere. I'll admit that my Modula-2 knowledge isn't great.

Would a message like 'only procedures can be used in top-level statements, not functions' be better?

**Comment by dram** [comment]
Sorry, I misunderstood it.

Yes, I think your version is better.

BTW, according to chapter 10 of the language report, it would be better to use *proper procedures* instead of *procedures*, and *function procedures* instead of *functions*.

**Comment by davidgiven** [comment]
OK --- done. Thanks for the report!
