### ISSUE TITLE
Undefined `_execve` for Unix module of Modula-2

### ISSUE THREAD

**Issue by dram** [davidgiven/ack#31]
When compiling following code:

```
MODULE test;

IMPORT Unix;

VAR
  r: INTEGER;
BEGIN
  r := Unix.execve (NIL, NIL, NIL);
END test.
```

ACK reports an error:

```
"test.mod", line 9: (warning) variable "r" never used
Undefined:
        _execve
```

**Comment by dram** [comment]
After adding a new file `plat/linux/libsys/execve.c` with following content, previous example can be compiled successfully:

```
#include <unistd.h>
#include "libsys.h"

int execve(const char *path, char *const argv[], char *const envp[])
{
        return _syscall(__NR_execve, (quad) path, (quad) argv, (quad) envp);
}
```

The signature is copy from [Open Group Base Specifications](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exec.html). Not sure if it also needs to be added to `plat/linux396/include/unistd.h` and `plat/linuxppc/include/unistd.h`.

BTW, I'm curious and can not figure out the relation between `plat` and `mach` directory, as I also find file `i386/libsys/execve.s` in `mach`.

**Comment by dram** [comment]
I kind of think that declaration is needed for `unistd.h`, which is needed for C code when using this function.

Create a PR #32 for this system call.

**Comment by davidgiven** [comment]
PR merged. Thanks!

**Comment by kernigh** [comment]
The files in mach/i386/libsys were for some old system, perhaps Xenix. (A comment in mach/i386/cv/cv.c mentions "XENIX386".) We can't use them with Linux. Now the plat/ directory has libsys and boot.s for our current platforms, while mach/ has assemblers and code generators. But mach/ also has artifacts like old libsys.

Linux has many system calls, and our libsys still doesn't provide most of them.
