### ISSUE TITLE
C preprocessor doesn't handle the last line of a file not having a newline properly and crashes

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [davidgiven/ack#310]
I am no longer able to compile my games with ack (https://github.com/Fabrizio-Caruso/CROSS-LIB).

It fails with this file:
https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/src/cross_lib/display/display_macros.c

In particular the preprocess has a problem with `#asm` and `#endasm` inside `#if defined` which is not supposed to enter (it is false).
It also detects a false missing `#endif` (even if `#asm` and `#endasm` are removed).

It fails with these errors:
```
"cross_lib/display/display_macros.c", line 252: (warning) asm: unknown control
"cross_lib/display/display_macros.c", line 258: (warning) endasm: unknown control
"cross_lib/display/display_macros.c", line 604: (warning) missing #endif
```

This can be reproduced by cloning Cross-Lib (https://github.com/Fabrizio-Caruso/CROSS-LIB), installing Makefile, Python and ACK and running `xl chase pc8086`

**Comment by davidgiven** [comment]
Do you know when this last worked? Because nothing's changed with the C preprocessor for a long time.

Also, the messages you quote are warnings and shouldn't (probably) cause the compilation to fail. Can you paste the entire output?

**Comment by Fabrizio-Caruso** [comment]
My project has evolved in the meanwhile. So I cannot be sure that the very same current source code would work with a previous version. What I am sure about is that my current code can be compiled with more than a dozen other compilers.
Maybe my code uses too many nested directives for ack. Is it possible?

```
cross_lib/display/display_macros.c cross_lib/input/input_macros.c cross_lib/sleep/sleep_macros.c games/chase/split_files/move_player.c games/chase/split_files/ghost.c  games/chase/split_files/level.c games/chase/split_files/character.c games/chase/split_files/game_text.c games/chase/split_files/main.c games/chase/split_files/init_images.c games/chase/split_files/strategy.c
"cross_lib/display/display_macros.c", line 246: (warning) asm: unknown control
"cross_lib/display/display_macros.c", line 252: (warning) endasm: unknown control
"cross_lib/display/display_macros.c", line 598: (warning) missing #endif
assertion "nestlevel > svnestlevel[nestcount]" failed: file "lang/cem/cpp.ansi/domacro.c", line 305, function: skip_block
                                                                                                                         ack: c:/ack/lib/ack/cpp.ansi died with signal 6
Pre-processor failed
make: *** [makefiles.common/targets/ack/Makefile.ack_targets:19: pc8086_tiny_buffered] Error 1
```

**Comment by davidgiven** [comment]
Yes, the preprocessor is crashing. It shouldn't do that.

The problem is that you don't have a trailing newline after the last line of the file. This is triggering some weirdness. The minimum test case is:

```
#if 0
#endif // no trailing newline
```

I've had a look at the preprocessor code but fixing it seems to be non-trivial due to a design issue, and I'll need to think about it more, but your workaround should be easy.
