### ISSUE TITLE
Long module names support for Modula-2

### ISSUE THREAD

**Issue by dram** [davidgiven/ack#33]
It seems that ACK do not support long module names for Modula-2, e.g.:

```
MODULE test;

IMPORT FooBarBazQux;

BEGIN
END test.
```

According to `strace` output, when compiling this example, ACK will try to open file `FooBarBazQ.def` instead of `FooBarBazQux.def`.

**Comment by dram** [comment]
Module [Conversions](https://github.com/davidgiven/ack/blob/decf0f5e9c032b952223acb469a5a544af460c76/lang/m2/libm2/Conversion.def) is also affected by this limit, with its file base names stripped to 10 characters.

**Comment by davidgiven** [comment]
Yes --- from defmodule.c:

	char buf[15];
	char *strncpy(), *strcat();

	strncpy(buf, name, 10);
	buf[10] = '\0';			/* maximum length */
	strcat(buf, ".def");

Aargh. Will fix.

**Comment by davidgiven** [comment]
Fixed by 893471a42eb4d189cc0ba1dac1864d6f151bccd7. I also renamed the source files for Conversions and RealConversions (which were truncated to match).

The reason for this was most likely because early versions of Minix only supported 14 character filenames.
