### ISSUE TITLE
left out debug message when compiling multiple files?

### ISSUE THREAD

**Issue by dram** [davidgiven/ack#34]
When compiling more than one files, it seems that some debug messages are left out, e.g.:

```
% ack -o test foo.c bar.c
foo.c
bar.c
```

ACK will be silent if only one file is specified.

**Comment by davidgiven** [comment]
Actually I think that's intentional, as gcc used to do this too.

But it doesn't any more, so removed in 62022c6f6b5d0bc06b2f45c9e3a43ddce669c023.
