### ISSUE TITLE
Add ".pas" to "lib/descr/fe" for Pascal

### ISSUE THREAD

**Issue by dram** [davidgiven/ack#41]
I find that current days most Pascal source files are saved with ".pas" extension, it would be nice to make ACK support it.

BTW, does `ack` have any option to specifiy compiler directly instead of relying on file name?

**Comment by davidgiven** [comment]
Yes, you use the confusingly name -. option:

    ack -mlinux386 -c -.p actually-a-pascal-file-honest.txt

Yes, changing the extension is reasonable; I'll add that to the todo list, but can't promise when.

**Comment by dram** [comment]
Sorry, I missed that in man page, but I run it with no success:

```
% ./ack -c -.p hello.pas
./ack: warning, Unknown suffix in hello.pas
led: hello.pas: wrong magic number (fatal)
```

**Comment by kernigh** [comment]
No, -.p does not request the Pascal compiler. It requests the Pascal runtime and library. (The runtime calls the program's main procedure.) If you did `ack -c.e file.p` and then `ack -.p file.e`, then the compiler would still take file.e as an EM file, not a Pascal file.

**Comment by davidgiven** [comment]
Sorry, yes, kernigh@ is quite right. I haven't spotted a way to force a file to be interpreted as a particular language. There should be one. Filed #48.

**Comment by davidgiven** [comment]
Obsolete.
