### ISSUE TITLE
confusing stack comments in mach/powerpc/libem

### ISSUE THREAD

**Issue by kernigh** [davidgiven/ack#42]
In a Forth comment like `( a b c -- d )`, I expect that c was on top of the stack. After commit e7e29d3, comments in powerpc/libem don't match my expectation.

Forth would ignore the comment, but Factor would parse it as a stack effect. The convention from [Factor's manual](http://docs.factorcode.org/content/article-effects.html) is, "Stack elements in a stack effect are ordered so that the top of the stack is on the right side." So in `( a b c -- d )`, the top is c.

mach/powerpc/libem/rck.s gives the comment `( descriptor value -- )`, but the code seems to load the descriptor from 0(sp) and the value from 4(sp), so the actual stack effect seems to be `( value descriptor -- )`.

libem/ior.s gives the comment `( size b a -- a+b )`, but the actual stack effect seems to be `( b a size -- a+b )`. In contrast, libem/csb.s gives the comment `( value tableaddr -- )`, and the actual stack effect seems to agree with the comment, with tableaddr as top.

**Comment by davidgiven** [comment]
Yeah, the comments are wrong. Sorry about that. Will fix.

**Comment by davidgiven** [comment]
Fixed as part of 81c677d218a3f14c8b94e9dbfca055ba27f6610a.
