### ISSUE TITLE
BASIC: _mid() can return uninitialized pointer

### ISSUE THREAD

**Issue by hexcoder-** [davidgiven/ack#54]
Hi,

cppcheck found this in function _mid()
[lang/basic/lib/string.c:161]: (error) Uninitialized variable: s2

IMO it is better to return(s) or call error() than to return an uninitialized pointer.

**Comment by davidgiven** [comment]
You're right, that's terrible. Although to be fair, it looks like that bug is 30 years old, and I suspect nobody used the BASIC compiler even when it was new...
