### ISSUE TITLE
resource leaks in readfile()

### ISSUE THREAD

**Issue by hexcoder-** [davidgiven/ack#55]
Hi,

cppcheck found a memory and a resource leak in readfile()
lang/cem/cemcom/mcomm.c:91

On return the file descriptor fd is leaked and the malloc()ed cbuf.

**Comment by kernigh** [comment]
This might not get fixed, because I believe that we don't build anything in `lang/cem/cemcom`. We only use the newer compiler in `lang/cem/cemcom.ansi`.

**Comment by davidgiven** [comment]
Correct. cemcom is the old K&R C compiler. It's worth having for historical value but it's now abandoned. (Everything that the K&R compiler would compile, the ANSI compiler will compile also.)

**Comment by davidgiven** [comment]
Correct. cemcom is the old K&R C compiler. It's worth having for historical value but it's now abandoned. (Everything that the K&R compiler would compile, the ANSI compiler will compile also.)
