### ISSUE TITLE
mcg calls getopt() in non-portable way

### ISSUE THREAD

**Issue by kernigh** [davidgiven/ack#64]
mach/proto/ncg/main.c, line 51:
```
        int c = getopt(argc, argv, "-d:D:C:o:");
```

The '-' in `"-d:D:C:o:"` is special to GNU libc or OpenBSD libc, and not portable to some other systems. mcg uses the special '-' to find its input file. I suspect that mcg would fail to find its input file when running on systems like FreeBSD.

The fix would look like my commit 50a7031, where I removed the special '-' from em_b and em_ego. I did not touch mcg because we now don't build mcg.

**Comment by kernigh** [comment]
I removed the special '-' in commit a60738a, which is part of pull request #73.

**Comment by davidgiven** [comment]
Okay, cheers --- this is now obsolete.
