### ISSUE TITLE
Travis CI doesn't use clang

### ISSUE THREAD

**Issue by kernigh** [davidgiven/ack#67]
I was looking at https://travis-ci.org/davidgiven/ack and noticed that clang's warnings look exactly like gcc's warnings. That's because the clang build uses gcc, not clang. The [sequence of commands](https://travis-ci.org/davidgiven/ack/jobs/301659553) is

```
$ export CC=clang
$ clang --version
$ make PREFIX=/tmp/acki +ack
```

but the Makefile's `CC = gcc` takes precedence over the environment's `CC=clang`.

**Comment by davidgiven** [comment]
Yikes.
