### ISSUE TITLE
infinite rebuilds after editing input to llgen

### ISSUE THREAD

**Issue by kernigh** [davidgiven/ack#68]
If I build ack, then edit any file that llgen takes as input, then the build system gets stuck in infinite rebuilds. These commands reproduce the problem:

```
$ gmake
$ touch lang/pc/comp/statement.g
$ gmake
$ gmake
```

I'm using ninja. The first `gmake` builds everything. After touching statement.g, the second `gmake` seems to succeed. It runs llgen and rebuilds everything that depends on llgen's output. The third `gmake` repeats the actions of the second `gmake`, by running llgen again and rebuilding the same things.

To stop the infinite rebuilds and work around this problem, I run `gmake clean`. The problem recurs whenever I edit a .g file, or when I edit a .c file and the build system generates a .g file from the .c file.

I observe that llgen succeeds without touching some of its output files; this might be confusing ninja.

```
$ ls -l lang/pc/comp/statement.g                                               
-rw-r--r--  1 kernigh  kernigh  9276 Nov 14 14:53 lang/pc/comp/statement.g
$ cd ../ack-build/obj                                                          
$ ls -l lang/pc/comp/llgen/                                                    
total 312
-rw-r--r--  1 kernigh  kernigh  14207 Nov 13 22:15 Lpars.c
-rw-r--r--  1 kernigh  kernigh    959 Nov 13 22:15 Lpars.h
-rw-r--r--  1 kernigh  kernigh  62723 Nov 13 22:15 declar.c
-rw-r--r--  1 kernigh  kernigh  24979 Nov 13 22:15 expression.c
-rw-r--r--  1 kernigh  kernigh   5335 Nov 13 22:15 program.c
-rw-r--r--  1 kernigh  kernigh  29180 Nov 13 22:15 statement.c
-rw-------  1 kernigh  kernigh   1728 Nov 13 22:15 tokenfile.c
```

**Comment by davidgiven** [comment]
Ugh. I loathe build systems...

It looks like llgen has some logic where it doesn't update file timestamps unless the content changes, and this is confusing ninja. (ninja -t browse and ninja -d explain are really useful here.)

Changing the util/LLgen/build.lua to:

    "cd %{dir} && rm -f %{outs} && %{abspath(ins)}"

...appears to solve the problem.

**Comment by davidgiven** [comment]
Fixed --- thanks for producing a test case for this (I'd noticed something weird here, but never tracked it down).
