### ISSUE TITLE
obstacles to build ack on macOS

### ISSUE THREAD

**Issue by kernigh** [davidgiven/ack#74]
It is not yet possible to build ack on macOS using Apple's compiler. I list some obstacles; there may be other obstacles.

### clang and traditional C
In recent versions of macOS, Apple's compiler is clang. There is a `gcc` link that just calls clang. (Some users [mistakingly believe that this compiler is gcc](https://stackoverflow.com/questions/9353444/how-to-use-install-gcc-on-mac-os-x-10-8-xcode-4-4). It isn't.)

Right now, clang can't build ack. The problem is that clang makes errors in traditional C code that uses `return;` in functions with an implicit `int` return type. Such code exists because traditional C had no `void` type. I used clang 4.0.0 on OpenBSD 6.2 to build ack from October 2017, but switched to gcc 4.9.4 in February 2018, because the new plat/pdpv7 enabled some traditional C code where clang makes errors.

My old PowerPC machine has Mac OS X 10.4 and Xcode 2.5, where Apple's compiler was gcc 4.2.1, not clang.

### case-insensitive filesystem
Mac filesystems are almost always case-insensitive. This is bug #58 (Does not build on case insensitive filesystems), possibly fixed in commit a1043bc, but no person confirmed that ack now builds on any case-insensitive filesystem.

### Apple sbrk()
The sbrk() function in Apple's libc has [a limit of only 4 megabytes](https://opensource.apple.com/source/Libc/Libc-1244.30.3/emulated/brk.c.auto.html). If any ack tool uses sbrk(), it might run out of memory.

- util/led uses sbrk() to allocate memory. One might need to switch it from sbrk() to malloc().
- util/opt already uses malloc() instead of sbrk() by default.
- util/LLgen and util/ncgg call sbrk() to measure memory usage. This is not an obstacle if the measurement is wrong but the tool still works. I have seen ncgg reporting "0K heap used" in OpenBSD, because malloc() used mmap(), not sbrk().

### common symbols in static libraries
By default, [Apple's archiver doesn't index common symbols in static libraries](https://stackoverflow.com/questions/44343859/symbol-not-found-when-static-linking-on-macosx). This caused a linker error that stopped the build in my old Mac.

I started the build because my old Mac has gcc, not clang. The system's GNU make 3.80 is too old for our top Makefile, so I compiled and used GNU make 4.2.1. (Newer versions of macOS have GNU make 3.81, which might be new enough.) For util/ack, our build system puts the .o files in a static library with `ar cqs out.a in.o...`, then links the executable. The symbols from data.c went missing because data.o had only common symbols. So I got a linker error.

The manual says that libtool -c or ranlib -c can index the common symbols. (This manual says so in my old Mac, but also in a newer cctools from https://opensource.apple.com/.) The command would be `ar cqS out.a in.o... && ranlib -c out.a` or `/usr/bin/libtool -c -static -o out.a in.o...`. The latter must run Apple libtool, not GNU libtool.

**Comment by ccodere** [comment]
Regarding the issue with ACK utility and static library and common symbols, a workaround is to add the following to build.lua of util/ack and it solved my issue, but it cause other problems on other platforms:

`	vars = {
		["+cflags"] = {"-fno-common"}
	}`

**Comment by davidgiven** [comment]
I've actually just been looking at this. In the specific case of util/ack/data.c, it should be an easy workaround, but of course I don't know what else there might be. (I don't have an OSX machine so have to do all my compilation on Travis...) I think the best option is to remove the use of COMMON completely, as they're problematic.

See https://github.com/davidgiven/ack/pull/152.

**Comment by davidgiven** [comment]
...also, I recently got things working on Cygwin (and enabled Appveyor CI for github pushes), so the brk/sbrk change has really helped there. I'm hopeful that making OSX work shouldn't be _too_ hard.

**Comment by davidgiven** [comment]
It builds! Woohoo! Although it does take Travis 17 minutes, which is even slower than Appveyor's 12 for the Cygwin build.

kernigh@: thank you very much for the writeup and for doing the sbrk stuff, which were the key bits of this --- sorry it took so long until I got around to making it work...
