### ISSUE TITLE
lang/cem/libcc.ansi/misc/termcap.c:65]: (error) Resource leak: fp

### ISSUE THREAD

**Issue by dcb314** [davidgiven/ack#75]
Source code is

       if (fgets(cp, 1024, fp) == NULL)
                return (0);

There is a call to fclose(fp) a few lines later the same function. Why not here ?

**Comment by dcb314** [comment]
lang/cem/libcc/stdio/termcap.c:67]: (error) Resource leak: fp

Same thing in different file.

**Comment by davidgiven** [comment]
Thanks --- actually, neither of these are used (the termcap library's not built. Not entirely sure why). But I've fixed and ANSI one; the K&R libc is beyond help so I'm not touching it.
