### ISSUE TITLE
util/flex/ecs.c:317]: (style) Array index 'cclp' is used before limits check.

### ISSUE THREAD

**Issue by dcb314** [davidgiven/ack#76]
Source code is

      for ( ++cclp; cclflags[cclp] && cclp < lenccl; ++cclp )

Suggest check limit before use not after, like this:

      for ( ++cclp; (cclp < lenccl) && cclflags[cclp]; ++cclp )

**Comment by davidgiven** [comment]
Yup, that's awful. But that flex isn't used, or even built (the system flex is used instead), so I'm not going to touch it --- fixing _all_ the antiquated code is far too big a rabbit hole for me... thanks for reporting it, though!
