### ISSUE TITLE
util/ego/cs/cs_profit.c:75: dangerous call to fscanf

### ISSUE THREAD

**Issue by dcb314** [davidgiven/ack#79]
util/ego/cs/cs_profit.c:75]: (warning) fscanf() without field width limits can crash with huge input data.

Source code is

      fscanf(f, "%s", s);

maybe better code

      fscanf(f, "%100s", s);

**Comment by dcb314** [comment]
util/ego/sp/sp.c:63]: (warning) fscanf() without field width limits can crash with huge input data.

Same thing somewhere near.

**Comment by davidgiven** [comment]
There's actually a bunch. The entire ego config file parser is awful (#86). But thanks; I've fixed most of them (others are harder).
