### ISSUE TITLE
ed scripts don't work on ed > 1.10

### ISSUE THREAD

**Issue by davidgiven** [davidgiven/ack#84]
It looks like new versions of ed have subtly changed the language and the complex ed scripts in the ACK don't work properly any more.

**Comment by kernigh** [comment]
The version number might be for [GNU ed](https://www.gnu.org/software/ed/), which passed 0.10 and reached 0.14.2. I had no problems with BSD ed from OpenBSD 6.3. I don't know about Heirloom/illumos ed.

**Comment by davidgiven** [comment]
Sorry, yeah, that was GNU ed. I actually ended up adopting the Minix 2 ed into the distribution as that was easier than rewriting the ed scripts. (Which do things which are expressly forbidden by POSIX.)
