### ISSUE TITLE
Compilation failure on cygwin

### ISSUE THREAD

**Issue by davidgiven** [davidgiven/ack#88]
ACK doesn't build on cygwin. Removing the ed dependency helps a lot, but now I'm running into an issue because `brk` isn't supported --- led uses it. Luckily it seems that led is written to use `sbrk`, and only uses `brk` because of a v7 bug workaround.

**Comment by kernigh** [comment]
I want to avoid `brk` and `sbrk` because of macOS (issue #74), where Apple's `sbrk` has a limit of 4 megabytes. I would need to teach util/led to use malloc, but I haven't done so. I would be fine with fixing Cygwin and leaving macOS for later.
