### ISSUE TITLE
linux68k-dup_e fails because of cuu

### ISSUE THREAD

**Issue by kernigh** [davidgiven/ack#97]
Our new emulator for linux68k shows that `tests/plat/core/dup_e.e` fails. I also reproduced the failure in another emulator, ARAnyM running Debian Linux.

I wrote dup_e.e to test the EM instructions *dup* and *dus*, but the failure is because of *cuu* in this EM code to load an unsigned 2-byte integer from a global variable:

```
    lae size
    loi 2
    loc 2
    loc EM_WSIZE
    cuu
    dus EM_WSIZE  /* 3rd copy */
```

I intended to convert the unsigned integer from 2 bytes to the word size, because *dus* expects a word. EM's word size is 4 bytes on m68020. EM's stack operates on words, so `loi 2` must push the 2-byte value as a word. I don't know the high bytes of this word. I would set the high bytes using `loc 2 loc 4 cii` to get a signed word or `loc 2 loc 4 cuu` to get an unsigned word.

The 68k code from `ack -mlinux68k -c.s dup_e.e` has

```
clr.l d0
move.w (_size),d0
move.l d0,-(sp)
pea (2)
pea (4)
jsr (.cuu)
move.l (sp)+,d0
lea (0,sp,d0.l*1),a0
asr.l #2,d0
beq 2f
1:
move.l -(a0),-(sp)
sub.l #1,d0
bne 1b
2:
```

If I comment out `pea (2)`, `pea (4)`, `jsr (.cuu)`, then the test passes. Therefore, `loc 2 loc 4 cuu` doesn't work. The 68k code uses `clr.l d0` (to set d0 to zero) then `move.w (_size),d0` (to move the 2 bytes into d0), so d0 is in fact an unsigned word, and the next call to `.cuu` is not needed. I don't know if `loi 2` pushes an unsigned word on all platforms, so I don't know whether to remove the *cuu* from the EM code.

I also don't know if *cuu* instructions from our compilers work on m68020.

**Comment by davidgiven** [comment]
It took a while to find, but this is actually specified --- this is from the em whitepaper, section 2:

> The size of almost all objects in EM is an integral number of words. Only two operations are allowed on objects whose size is a divisor of the wordsize: push it onto the stack and pop it from the stack. The addressing of these objects in memory is always indirect. If such a small object is pushed onto the stack it is assumed to be a small integer and stored in the least significant part of a word. The rest of the word is cleared to zero, although EM provides a way to sign-extend a small integer.

So `loi 2` _should_ push an unsigned word.

There's a comment at the top of the `cuu` routine saying that it only converts between multiples of four. This suggests that this has _never_ worked. I do see that there are some rules that drop unnecessary conversions, but they are only included if WORD_SIZE is 2. I'll do some playing.

**Comment by davidgiven** [comment]
Okay, there's a potential fix in https://github.com/davidgiven/ack/pull/98. The test pass, but you know ncg better than I do --- PTAL.

**Comment by kernigh** [comment]
I now think that the fix in #98 isn't needed because the test is wrong -- `loc 2 loc 4 cuu` is illegal when word size is 4, and would [raise EILLINS in the interpreter (util/int)](https://github.com/davidgiven/ack/blob/7edc8356262dfba660605b024d5c2dac36fdce7e/util/int/do_conv.c#L328). The C compiler and Modula-2 compiler don't emit such code. In these compilers, the sizes for *cuu*, *cui*, and *ciu* are at least the word size; see [conversion() in C](https://github.com/davidgiven/ack/blob/7edc8356262dfba660605b024d5c2dac36fdce7e/lang/cem/cemcom.ansi/conversion.c#L32) and [CodeCoercion() in Modula-2](https://github.com/davidgiven/ack/blob/7edc8356262dfba660605b024d5c2dac36fdce7e/lang/m2/comp/code.c#L176). For example, when the C compiler promotes `unsigned char` to `int`, the conversion is `loc 4 loc 4 cui`, not `loc 1 loc 4 cui`.

The test (dup_e.e) passes on PowerPC because my commit 504d2aa changed mach/powerpc/ncg/table to pass the test. This change might be wrong.

The test fails on i386. I haven't been running the tests on i386, but just now, I compiled the test for osx386 and copied it to a Mac, where it failed. The code from ncg corrupts the stack. It drops the `cuu` in `loc 2 loc 4 cuu`, leaving constants 2 and 4 on the stack. In the assembly code, the 20 (from global variable *size*) and the 2 stay on the stack, and the 4 gets passed as the size to .dup.

```
mov ecx,20
call .dup
mov ecx,4
movzx eax,(_size)
push eax
push 2
call .dup
```

I will try to edit the test.

**Comment by kernigh** [comment]
The fix that works for me (on linux68k and osx386) is to delete these 3 lines:

```diff
diff --git a/tests/plat/core/dup_e.e b/tests/plat/core/dup_e.e
index 649589d84..1f7ab6289 100644
--- a/tests/plat/core/dup_e.e
+++ b/tests/plat/core/dup_e.e
@@ -25,9 +25,6 @@ size
     dup 20        /* 2nd copy */
     lae size
     loi 2
-    loc 2
-    loc EM_WSIZE
-    cuu
     dus EM_WSIZE  /* 3rd copy */
 
     cal $check
```

This change is small, so I won't make a pull request. The other instances of *cuu* and *cii* in the .e tests look correct to me.

**Comment by davidgiven** [comment]
That's odd --- if cui and cuu don't allow a size of 2 when the wordsize is 4, how is sign extension done?

(On phone, will apply your change the next time I get WiFi.)

**Comment by kernigh** [comment]
*cii* does sign extension, the input size to *cii* can be smaller than a word. *ciu* doesn't do sign extension. The C compiler, given `signed char c`, does `(unsigned int)c` using `loc 1 loc 4 cii loc 4 loc 4 ciu`.

The EM spec shows this with Pascal code: `cii:` in http://tack.sourceforge.net/olddocs/em.pdf checks `t<wsize` and does sign extension. The other conversions use `szindex(...)` to trap EILLINS unless the input size is 1 or 2 words. (In the EM spec, the conversions also trap EILLINS with unsigned 2-word integers. The EM spec only has signed 1-word, signed 2-word, and unsigned 1-word integers.)

**Comment by davidgiven** [comment]
Fair enough.(It'd never occur to me to use cii for sign extension...) Merged and closed. Thanks!
